export const SUMMARY_DATA = "SUMMARY_DATA";

export const CAMPAIGN_STATUS = "CAMPAIGN_STATUS";

export const DONATION_TRENDS = "DONATION_TRENDS";

export const VOLUNTEER_TRENDS = "VOLUNTEER_TRENDS";

export const CAMPAIGN_DONATIONS = "CAMPAIGN_DONATIONS";
