export const CAMPAIGNS_DATA = "CAMPAIGNS_DATA";

export const CAMPAIGNS_PAGINATED = "CAMPAIGNS_PAGINATED";

export const CAMPAIGN_METADATA = "CAMPAIGN_METADATA";

export const CAMPAIGN_BY_ID = "CAMPAIGN_BY_ID";

