export const SAVE_USER_DATA = "SAVE_USER_DATA";

export const SAVE_USER_DATA_BYID = "SAVE_USER_DATA_BYID";

export const DONATIONS_BY_ID = "DONATIONS_BY_ID";

export const DONATIONSBYID_METADATA = "DONATIONSBYID_METADATA";
